name: Windows MSVC Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgDirectory: '${{ runner.workspace }}/vcpkg'
          vcpkgJsonGlob: '**/vcpkg.json'

      - name: Configure VCPKG_ROOT env var
        run: echo "VCPKG_ROOT=${{ runner.workspace }}/vcpkg" >> $env:GITHUB_ENV

      - name: Set up MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Build solution
        run: msbuild msvc/dataforge.sln /p:Configuration=Release

      - name: Run tests
        run: |
          cd msvc/x64/Release
          .\dataforge_tests.exe
